FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
  cmake \
  build-essential \
  python3-dev \
  libboost-all-dev \
  libopenblas-dev \
  && rm -rf /var/lib/apt/lists/*


COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY uv.lock .
COPY pyproject.toml .

RUN uv sync

COPY src src

EXPOSE 7000

CMD [".venv/bin/fastapi", "run", "src/server.py", "--port=7000"]
